services:
  postgresql:
    image: postgres:16
    ports:
      - "6543:5432"
    environment:
      POSTGRES_DB: estate_agency
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    volumes:
      - postgresql:/var/lib/postgresql/data

volumes:
  postgresql: { }

networks:
  backend: { }